# Dependencies
markdown:         redcarpet
pygments:         false

# Permalinks
permalink:        pretty

# Setup
title:            Gordon Stewart
tagline:          
url:              http://gstew5.github.io
paginate:         1
baseurl:          /
author:
  name:           Gordon Stewart
  url:            http://www.cs.princeton.edu/~jsseven
  email:          gstew5@gmail.com

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
